title: Project Workspace
url: "https://mariondugue.github.io"
baseurl: "/AMMITY-milestones"

collections:
  articles:
    output: true
    permalink: /menstruation/:title/

defaults:
  - scope:
      path: "_articles"
    values:
      layout: "article"
