title: Project Workspace
baseurl: "/AMMITY-milestones" 
url: "https://mariondugue.github.io"

collections:
  articles:
    output: true
    permalink: /menstruation/:title/

defaults:
  - scope:
      path: "_articles"
    values:
      layout: "article"
